version: '3.6'

services:

  app:
    container_name: app
    network_mode: host
    command: bash -c "python manage.py runserver 0.0.0.0:5000"
    build:
      context: .
    ports:
      - "5000:5000"
    env_file:
      - app/src/.env
    deploy:
      resources:
        limits:
          memory: 300M
