version: '3.6'
services:

  app:
    container_name: app
    build:
      context: .
    ports:
      - "9000:9000"
    env_file:
      - tizza/.env
    deploy:
      resources:
        limits:
          memory: 300M
